version: '3'
services:
    app:
        build: .
        ports:
            - "8080:8080"
            - "8000:8000"
            - "9001:9001"
        volumes:
            - .:/app
            - ./venv:/app/venv
        env_file:
            - .env